### ISSUE TITLE
Broken link on Introduction to JAX by Kevin Murphy

### ISSUE THREAD

**Issue by gerdm** [n2cholas/awesome-jax#31]
Clicking the link takes me to this error

<img width="957" alt="image" src="https://user-images.githubusercontent.com/4108759/122118821-67c26300-ce20-11eb-8f0c-226afc904f03.png">

**Comment by gerdm** [comment]
It might've changed for this one: `https://github.com/probml/pyprobml/blob/master/notebooks/jax_intro.ipynb`

**Comment by n2cholas** [comment]
> It might've changed for this one: `https://github.com/probml/pyprobml/blob/master/notebooks/jax_intro.ipynb`

Yep, this looks like the right one! Can you open a PR with this change?
