### ISSUE TITLE
A 'people' section?

### ISSUE THREAD

**Issue by bilal2vec** [n2cholas/awesome-jax#7]
Hey would adding a "people" section to the repository with a list of jax maintainers/devs/enthusiasts/blogs be a good idea?

**Comment by n2cholas** [comment]
First issue 🎉.

Good question, did you have specific people in mind? Maintainers/Devs are visible in the JAX repo. Most enthusiasts/blogs won't be doing stuff _only_ on JAX, so I'm not sure if it makes sense to link them here (we can link their relevant content). If there is a blog (not necessarily a person) focusing solely on JAX, that would be worth linking. 

Any thoughts on that?

**Comment by n2cholas** [comment]
@bilal2vec I'll close this for now due to inactivity, but feel free to reopen it if needed.
